sudo: true
dist: focal

language: python

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/ossl-2/

# Only build master, the version branches (e.g. 1.7.x), and
# version tags (which are apparently considered branches by travis)
branches:
    only:
        - master
        - /^\d+\.\d+\.x$/
        - /^\d+\.\d+(\.\d+)?$/

matrix:
    include:
        # Setting 'python' is just to make travis's UI a bit prettier
        - python: 3.8
          env: TOXENV=docs
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - python: 3.8
          env: TOXENV=docs-linkcheck
          if: (branch = master AND type != pull_request) OR commit_message =~ /linkcheck/

        # TODO: This needs to be moved to GHA, but it fails there. The
        # confusing part is why it passes on Travis!
        - python: 3.7
          env: DOWNSTREAM=paramiko

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh
