sudo: true
dist: focal

language: python

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/ossl-2/

# Only build master, the version branches (e.g. 1.7.x), and
# version tags (which are apparently considered branches by travis)
branches:
    only:
        - master
        - /^\d+\.\d+\.x$/
        - /^\d+\.\d+(\.\d+)?$/

matrix:
    include:
        - python: 3.8
          env: TOXENV=pep8,packaging
        # Setting 'python' is just to make travis's UI a bit prettier
        - python: 3.6
          env: TOXENV=py36
        - python: 3.9
          env: TOXENV=py39
          # Travis lists available Pythons (including PyPy) by arch and distro here:
          # https://docs.travis-ci.com/user/languages/python/#python-versions
        - python: pypy2.7-7.3.1
          env: TOXENV=pypy-nocoverage
        - python: pypy3.6-7.3.1
          env: TOXENV=pypy3-nocoverage
        - python: 2.7
          env: TOXENV=py27 OPENSSL=1.1.0l
        - python: 2.7
          env: TOXENV=py27-ssh OPENSSL=1.1.0l
        - python: 3.8
          env: TOXENV=py38 OPENSSL=1.1.0l
        - python: 2.7
          env: TOXENV=py27 OPENSSL=1.1.1h
        - python: 3.8
          env: TOXENV=py38 OPENSSL=1.1.1h
        - python: 3.8
          env: TOXENV=py38 OPENSSL=1.1.1h OPENSSL_CONFIG_FLAGS="no-engine no-rc2 no-srtp no-ct"
        - python: 3.8
          env: TOXENV=py38-ssh OPENSSL=1.1.1h
        - python: 3.8
          env: TOXENV=py38 LIBRESSL=2.9.2
        - python: 3.8
          env: TOXENV=py38 LIBRESSL=3.0.2
        - python: 3.8
          env: TOXENV=py38 LIBRESSL=3.1.4
        - python: 3.8
          env: TOXENV=py38 LIBRESSL=3.2.2

        - python: 3.8
          env: TOXENV=docs
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - python: 3.8
          env: TOXENV=docs-linkcheck
          if: (branch = master AND type != pull_request) OR commit_message =~ /linkcheck/

        # TODO: This needs to be moved to GHA, but it fails there. The
        # confusing part is why it passes on Travis!
        - python: 3.7
          env: DOWNSTREAM=paramiko

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            # This is set to a secure variable to prevent forks from notifying the
            # IRC channel whenever they fail a build. This can be removed when travis
            # implements https://github.com/travis-ci/travis-ci/issues/1094.
            # The value encrypted here was created via
            # travis encrypt "irc.freenode.org#cryptography-dev"
            - secure: "A93qvTOlwlMK5WoEvZQ5jQ8Z4Hd0JpeO53WYt8iIJ3s/L6AubkfiN7gwhThRtPnPx7DVMenoKRMlcRg76/ICvXEViVnGgXFjsypF0CzVcIay9pPdjpZjZHP735yLfX512RtxYEdEGwi5r25Z2CEFaydhhxNwfuMxGBtLUjusix4="
        use_notice: true
        skip_join: true
